### ISSUE TITLE
download function confused by other non-supported GPL-platform types 

### ISSUE THREAD

**Issue by marcmaxson** [LifeEGX/methylprep#25]
## Sample: BS_NS_BAL_641 has unrecognized platform

`python -m methylprep -v download -i GSE133062 -d ../GSE133062`

```
INFO:methylprep.download.geo:Downloaded and unpacked GSE133062
Traceback (most recent call last):
  File "/Users/mmaxmeister/anaconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/mmaxmeister/anaconda3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/mmaxmeister/methylprep/methylprep/__main__.py", line 6, in <module>
    cli_app()
  File "/Users/mmaxmeister/methylprep/methylprep/cli.py", line 240, in cli_app
    build_parser()
  File "/Users/mmaxmeister/methylprep/methylprep/cli.py", line 58, in build_parser
    parsed_args.func(func_args)
  File "/Users/mmaxmeister/methylprep/methylprep/cli.py", line 232, in cli_download
    run_series(args.id, args.data_dir, dict_only=args.dict_only)
  File "/Users/mmaxmeister/methylprep/methylprep/download/process_data.py", line 64, in run_series
    seen_platforms = geo_metadata(id, series_path, GEO_PLATFORMS, str(path))
  File "/Users/mmaxmeister/methylprep/methylprep/download/geo.py", line 151, in geo_metadata
    raise ValueError(f'Sample: {title} has unrecognized platform: {platform}')
ValueError: Sample: BS_NS_BAL_641 has unrecognized platform: GPL23976
```

**Comment by marcmaxson** [comment]
GPL23976 is another array with 750k probes, but apparently doesn't measure methylation. So it should ignore these samples.

**Comment by marcmaxson** [comment]
I think this is resolved, and this error only happens when the properly formatted IDAT files for a supported array type are not present. Gives more error message detail when it happens, such as the types of files it did find.
